export class Ticket {
  constructor(
    etat2: string,
    donneur4: string,
    client4: string,
    addr1input: string,
    ville1input: string,
    infoinput: string,
    telfixe1: string,
    telportable1: string,
    respons1input: string,
    typecontrat1: string,
    technicien5: string,
    technicien6: string,
    technicien7: string,
    technicien8: string,
    dateappel3: string,
    hinter: string,
    dinterv: string,
    typemat5: string,
    matri2input: string,
    descripanne: string,
    descritravail1: string,
    forfaitinput: string,
    quan1input: string,
    oeuvreinput: string,
    quan2input: string,
    pieceinput: string,
    quan3input: string,
    harrive: string,
    hdep: string,
    rq: string,
    fiche: string,
    id_ticket?: number
    ) {}
}
