export class TicketInterv {
  constructor(
    etat2: string,
    donneur4: string,
    client4: string,
    addr1input: string,
    ville1input: string,
    info1input: string,
    telfixe1: string,
    telportable1: string,
    respons1input: string,
    typecontrat1: string,
    technicien5: string,
    technicien6: string,
    technicien7: string,
    technicien8: string,
    dateappel3: string,
    hinterv: string,
    dinterv: string,
    typemat5: string,
    matri2input: string,
    descripanne: string,
    descritravail1: string,
    forfait1input: string,
    quan4input: string,
    oeuvre1input: string,
    quan5input: string,
    piece1input: string,
    quan6input: string,
    harrive1: string,
    hdep1: string,
    rq1: string
  ) {}
}
