export class Ticket {
  constructor(
    etat1: string,
    donneur3: string,
    client2: string,
    hfaddr: string,
    villeinput: string,
    infoinput: string,
    telfixe: string,
    telportable: string,
    responsinput: string,
    typecontrat: string,
    technicien1: string,
    technicien2: string,
    technicien3: string,
    technicien4: string,
    dateappel2: string,
    heureinterv: string,
    dateinterv: string,
    typemat4: string,
    matri1input: string,
    descrimat: string,
    descritravail: string,
    forfaitinput: string,
    quan1input: string,
    oeuvreinput: string,
    quan2input: string,
    pieceinput: string,
    quan3input: string,
    harrive: string,
    hdep: string,
    rq: string,
    fiche: string
    ) {}
}
